### ISSUE TITLE
File .env.example is missing from the repo

### ISSUE THREAD

**Issue by mcintyre94** [heybereket/oasis#25]
In `contributing.md` you mention:

> Go to the .env.example file where you can update the boiler text, as well as rename .env.example to .env

But I can't find this file anywhere in the repo: `find . -name .env.example`

When I run the app without a `.env` I get:

```json
{
    "code": "auth/invalid-api-key",
    "message": "Your API key is invalid, please check you have copied it correctly."
}
```

**Comment by heybereket** [comment]
Hey there! Sorry this might have been deleted while another pull request got merged. I've went ahead and recreated it!

**Comment by mcintyre94** [comment]
Thanks for such a quick fix! :)
