### ISSUE TITLE
"Back to top" button implementation

### ISSUE THREAD

**Issue by felipecespedes** [heybereket/oasis#33]
# Motivation
[Card](https://github.com/heybereket/oasis/projects/1#card-57558296)
As people scroll down the huge list, it maybe difficult to go all the way back to the top without refreshing, adding a "back to top" button can be an easier way to solve this.

# Expected results
1. The button will be visible after enough amount of scroll, otherwise, it will be hidden
2. The content of the button will be a white arrow up `^` icon (just to avoid translations)
3. The button theme will be dark
4. The button will be sticky on the lower right corner
5. When clicking on the button it will scroll to the top of the page using a smooth animation

## References
1. [This demo](https://codesandbox.io/s/0mnb8?file=/index.js:137-141) shows the intended functionality

# Implementation

## Components

`BackToTop` will be the component that contains all the logic to go back to the top of the page

## Possible libraries
1. [react-scroll-up-button](https://react-scroll-up-button.com/) 
**pros:** customizable, used by ~2k people, animation out of the box
**cons:** last updated 2 years ago
2. [react-easy-back-to-top](https://github.com/umutbozdag/react-easy-back-to-top)
**pros:** customizable
**cons:** lack of reference of projects using it
3. [Vanilla JS implementation](https://www.w3schools.com/howto/howto_js_scroll_to_top.asp)
**pros:** full control over the implementation
**cons:** more code to maintain, cross-browser compatibility issues could pop up 

# Notes
Open to suggestions, if everything is OK please let me know and happy to work on this

**Comment by heybereket** [comment]
Awesome, took a look at the mini demo, amazing, would be awesome to see this in production/live :)
