### ISSUE TITLE
Css bug: in the "/new" page

### ISSUE THREAD

**Issue by SudhamJayanthi** [heybereket/oasis#67]
The css got messed up and somehow things are left aligned on [https://oasis.sh/new](https://oasis.sh/new) page as in the screenshot. 

![screenshot showing bug](https://user-images.githubusercontent.com/67156051/113329661-75953b80-933b-11eb-92aa-ecc074fca5fb.png)

**Comment by uthmanigbin** [comment]
Seems to be happening to the /settings page as well.

![image](https://user-images.githubusercontent.com/21238502/113356619-34a52300-934b-11eb-9e13-48c264b3a43d.png)

**Comment by SowinskiMateusz** [comment]
done - fixes are pushed on prod
